version: "3"

services:

  esnode1:
    container_name: esnode1
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:      
      - ./certs:/usr/share/elasticsearch/config/certs
      - ./certs/esnode1:/usr/share/elasticsearch/config/certs/esnode1      
#      - ./es/data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200 
    environment:
      - discovery.type=single-node      
#      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      -  "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - node.name=esnode1
      - cluster.name=${CLUSTER_NAME}      
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/esnode1/esnode1.key
      - xpack.security.http.ssl.certificate=certs/esnode1/esnode1.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/esnode1/esnode1.key
      - xpack.security.transport.ssl.certificate=certs/esnode1/esnode1.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120

 

  kibana:
    container_name: kibana
    depends_on:
      - esnode1
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - ./certs:/usr/share/kibana/config/certs
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml 
    ports:
      - "5601:5601"
    environment:
     - SERVERNAME=kibana     
     - ELASTICSEARCH_HOSTS=https://esnode1:9200
     - ELASTICSEARCH_USERNAME=kibana_system
     - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
     - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
#    mem_limit: ${MEM_LIMIT}
#    healthcheck:
#      test:
#        [
#          "CMD-SHELL",
#          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
#        ]
#      interval: 10s
#      timeout: 10s
#      retries: 120
 
 